apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-go-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go
          image: hello-go
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
