apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold-task2
build:
  artifacts:
  - image: khaydarov95/otus-task2
    docker:
      dockerfile: ./simple-symfony-application/Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
