apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  databaseUrl: {{ printf "postgresql://%s:%s@%s:%s/%s?charset=utf8"
      .Values.postgres.access.user
      .Values.postgres.access.pass
      .Values.postgres.access.host
      .Values.postgres.access.port
      .Values.postgres.access.db | b64enc | quote }}