apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-postgres-statefulset
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          ports:
            - containerPort: {{ .Values.postgres.access.port }}
              name: postgredb
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.access.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.access.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.access.pass }}
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: manual
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres
  labels:
    app: {{ .Chart.Name }}-postgres
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.postgres.access.port }}
  selector:
    app: {{ .Chart.Name }}-postgres
